[theme]
mode = "dark"
source = "custom"
custom_palette = "Cyberdream"

[bar.default]
shadow = false
contact_shadow = false

[bar.default.monitor.main]
match = "XG27JCG"
enabled = true

[bar.default.monitor.secondary]
match = "MQ16FC"
enabled = false

[bar.default.monitor.builtin]
match = "Najing CEC Panda"
enabled = true

[bar.secondary.monitor.main]
match = "XG27JCG"
enabled = false

[bar.secondary.monitor.secondary]
match = "MQ16FC"
enabled = true

[bar.secondary.monitor.builtin]
match = "Najing CEC Panda"
enabled = false

[dock]
shadow = false

[shell.panel]
shadow = false

