[theme]
mode = "dark"
source = "custom"
custom_palette = "Cyberdream"

[bar.default]
shadow = false
contact_shadow = false

[bar.default.monitor.main]
match = "DP-1"
enabled = true

[bar.default.monitor.secondary]
match = "HDMI-A-1"
enabled = false

[bar.default.monitor.builtin]
match = "eDP-1"
enabled = true

[bar.secondary.monitor.main]
match = "DP-1"
enabled = false

[bar.secondary.monitor.secondary]
match = "HDMI-A-1"
enabled = true

[bar.secondary.monitor.builtin]
match = "eDP-1"
enabled = false

[dock]
shadow = false

[shell.panel]
shadow = false

