#!/usr/bin/env bash

output="$(
    wlr-randr |
        awk '/ASUS|ASUSTek|MQ16/ { print $1; exit }'
)"

[[ -z "$output" ]] && exit 1

transform="$(
    wlr-randr |
        awk -v output="$output" '
            $1 == output { found=1 }
            found && /Transform:/ {
                print $2
                exit
            }
        '
)"

case "$transform" in
    normal)
        wlr-randr --output "$output" --transform 90
        ;;
    90|270)
        wlr-randr --output "$output" --transform normal
        ;;
    *)
        wlr-randr --output "$output" --transform normal
        ;;
esac
