#!/usr/bin/env bash

if [ -n "$TMUX" ]; then
	tmux detach -E "bash -ic tmuxifier-sessionizer"
else
	if [[ $# -eq 1 ]]; then
		selected=$1
	else
		selected=$(find ~ ~/Work ~/Personal ~/School ~/Playground -mindepth 1 -maxdepth 1 -type d | tv --preview-command 'tree -C {} | head -n 10')
	fi

	[[ -z $selected ]] && exit 0

	selected_name=$(basename "$selected" | tr '. ' '__')

	if ! tmux has-session -t "$selected" 2>/dev/null; then
		TS_DIR="$selected" TS_NAME="$selected_name" tmuxifier load-session dev
	else
		tmux switch-client -t "$selected"
	fi
fi
