gui:
  theme:
    activeBorderColor:
      - "#78a8e8"
      - bold
    inactiveBorderColor:
      - "#7ed8e8"
    searchingActiveBorderColor:
      - "#b07ee8"
      - bold
    optionsTextColor:
      - "#7b8496"
    selectedLineBgColor:
      - "#272b2f"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#7b8496"
    cherryPickedCommitBgColor:
      - "#b07ee8"
    markedBaseCommitFgColor:
      - "#b07ee8"
    markedBaseCommitBgColor:
      - "#e8796f"
    unstagedChangesColor:
      - "#e8796f"
    defaultFgColor:
      - "#ffffff"
